### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ShotDead7297** [MisteFr/ScoreboardsPE#12]
24.10 00:49:21 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'ScoreboardsPE v1.0.2': Invalid argument supplied for foreach() on Miste\scoreboardspe\EventHandler
24.10 00:49:21 [Server] Server thread/CRITICAL ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "ScoreboardsPE-master/src/Miste/scoreboardspe/API/ScoreboardStore" at line 194

**Comment by MisteFr** [comment]
Hey @cujowilliams123,
Are you sure you are using the latest version of ScoreboardsPE ?
If yes can you describe me when that issue happens ? (If you are using the API or not).

**Comment by MisteFr** [comment]
@cujowilliams123 ?
