### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by KielKing** [MisteFr/ScoreboardsPE#13]
Hello, I've looked around and saw that there are no padding features on this API.
Could you add this to your to-do list?

**Comment by MisteFr** [comment]
Thanks for the feedback @KielKing.
Will look into that.

**Comment by KielKing** [comment]
Thanks for your time @MisteFr, hope it will help others too.

**Comment by KielKing** [comment]
For anyone who wants a simple temporary fix, this'll do:
```php
/* @var $scoreboard Scoreboard */
/* @var $player Player */
$text = str_pad("your text", 10); //Where 10 is the length of characters there is on your scoreboard's Title
$scoreboard->setLine($player, 1, $text); //Where the number is what line you want
```
