### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by KielKing** [MisteFr/ScoreboardsPE#14]
Hello again 😁 !

I was wondering if you could make a refresh function? right now I have to do 

Scoreboard->removeDisplay(Player)

then 

Scoreboard->addDisplay(Player)

 to refresh changes made to the scoreboard, and it's kind of buggy

it would be great if you could, and if you need assistance i'm always here 😄

**Comment by MisteFr** [comment]
What changes are you talking of ? Normally when you modify a line or rename the scoreboard the changes should be automatically sent.

**Comment by KielKing** [comment]
on my end the changes are not automatically sent, I have to removeDisplay then addDisplay

**Comment by MisteFr** [comment]
Do you mean sending the changes to all the online players who previously received the Scoreboard (because actually the changes are only sent to the player).

**Comment by KielKing** [comment]
yes, the new scoreboard does not send to the players I specified

**Comment by KielKing** [comment]
any updates on this?

**Comment by KielKing** [comment]
PS: i need this because i am using a repeating task to update values to the scoreboard

**Comment by KielKing** [comment]
bump
