### ISSUE TITLE
Big error onQuit()

### ISSUE THREAD

**Issue by KielKing** [MisteFr/ScoreboardsPE#15]
Error log:
[Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "ScoreboardsPE/src/Miste/scoreboardspe/API/ScoreboardStore" at line 194
[Server thread/DEBUG]: #0 ScoreboardsPE/src/Miste/scoreboardspe/API/ScoreboardStore(194): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string Invalid argument supplied for foreach(), string PocketMine\plugins\ScoreboardsPE\src\Miste\scoreboardspe\API\ScoreboardStore.php, integer 194, array Array())
[Server thread/DEBUG]: #1 ScoreboardsPE/src/Miste/scoreboardspe/EventHandler(25): Miste\scoreboardspe\API\ScoreboardStore->removePotentialViewer(string KielKing)
[Server thread/DEBUG]: #2 src/pocketmine/plugin/MethodEventExecutor(38): Miste\scoreboardspe\EventHandler->onQuitEvent(pocketmine\event\player\PlayerQuitEvent object)

client crashes after the first time they quit after the time server restarts because of this error

**Comment by KielKing** [comment]
bump @MisteFr

**Comment by KielKing** [comment]
bump @MisteFr

**Comment by MisteFr** [comment]
Hey @KielKing, 
Can you give me some infos about how can I reproduce this bug ?
Thanks !
