### ISSUE TITLE
erro client  accident

### ISSUE THREAD

**Issue by llronaldoll** [MisteFr/ScoreboardsPE#2]
How do I use the plugin?
When I try to enter the server, an accident happens !!

**Comment by MisteFr** [comment]
@llronaldoll You need to use the 1.7 branch of PocketMine-MP and your client version need to be 1.7.0.3 beta.

**Comment by llronaldoll** [comment]
@MisteFr   where do i get a pocketmine branch 1.7?

**Comment by MisteFr** [comment]
@llronaldoll You need to run PocketMine-MP from source, but please note that the scoreboards were added in 1.7 so you need a 1.7 client too.

**Comment by llronaldoll** [comment]
I do not know how to make a direct source .phar = (can it do for me?

**Comment by MisteFr** [comment]
You don't need a phar, juste delete your previous phar and place the src folder.
