### ISSUE TITLE
Refreshing the Scoreboard with RepeatingTasks doesn't work

### ISSUE THREAD

**Issue by Akuroma** [MisteFr/ScoreboardsPE#23]
I'm using a RepeatingTask to update the Scoreboard. For example to show the players ping to the player. I installed the newest version of this plugin, but now it doesn't work anymore. Old version (1.0.5) does work perfectly.

**Comment by iZeaoGamer** [comment]
Have you tried using $scoreboard->removeDisplay($player) and $scoreboard->addDisplay($player)?
That’s what I used in a scheduler task, and it works fine.
