### ISSUE TITLE
what the hell is $pk

### ISSUE THREAD

**Issue by rjworks** [MisteFr/ScoreboardsPE#26]
https://github.com/MisteFr/ScoreboardsPE/blob/eb03e934c76eeb7496935d14601946d68968da60/src/Miste/scoreboardspe/API/Scoreboard.php#L114

**Comment by IceCruelStuff** [comment]
https://github.com/MisteFr/ScoreboardsPE/blob/eb03e934c76eeb7496935d14601946d68968da60/src/Miste/scoreboardspe/API/Scoreboard.php#L92
