### ISSUE TITLE
Support for Altay Software

### ISSUE THREAD

**Issue by SuperKali** [MisteFr/ScoreboardsPE#5]
Thank you so much for this plugin api, please you can update this plugin for altay software?

**Comment by SuperKali** [comment]
Ok, it's normal, but pmmp doesn't have all features

**Comment by TobiasGrether** [comment]
I think you can use this plugin with Altay as with pmmp

**Comment by SuperKali** [comment]
@TobiasDevDE doesn’t work in altay

**Comment by SuperKali** [comment]
Thanks all for dislike

**Comment by FunnyBuddys** [comment]
It works for me http://prntscr.com/l7lxdp

**Comment by SuperKali** [comment]
@FunnyBuddys 

[12:22:01] [Server thread/CRITICAL]: Unhandled exception executing command 'scoreboard setLine @all test 1 BENVENUTO' in scoreboard: Undefined class constant 'TYPE_REMOVE'
[12:22:01] [Server thread/CRITICAL]: Error: "Undefined class constant 'TYPE_REMOVE'" (EXCEPTION) in "plugins/ScoreboardsPE/src/Miste/scoreboardspe/API/Scoreboard" at line 99

**Comment by SuperKali** [comment]
you can give me your version of scoreboard? @FunnyBuddys

**Comment by MisteFr** [comment]
I don’t plan to support Altay because I am not using it. If you want to use this plugin you will have to use PocketMine or update Altay correctly.

**Comment by TobiasGrether** [comment]
I will make the update in Altay

**Comment by TobiasGrether** [comment]
It should now work with Altay. If you have any other bugs regarding Altay, please create an issue on Altay Repo
