### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [MisteFr/ScoreboardsPE#7]

**Comment by SuperKali** [comment]
i have tried to update the board but isn't update

**Comment by MisteFr** [comment]
Hey @SonsaYT04,
Thanks for your feedback !
Can you post here the code you are using each time a player joins and then what you do in your task ?
Thanks

**Comment by SonsaYT04** [comment]
I used this to all player who joined, I don't know if it's correct? Creating New Scoreboard everytime when player joined

$scoreboard = new Scoreboard($this->getServer()->getPluginManager()->getPlugin("ScoreboardsPE")->getPlugin(), "§l§eHAPPY BEDROCK", ScoreboardAction::CREATE);
$scoreboard->create(ScoreboardDisplaySlot::SIDEBAR, ScoreboardSort::DESCENDING);
$scoreboard->addDisplay($player);
$scoreboard->setLine($player, 2, "§fName:");
$scoreboard->setLine($player, 3, "§a" . $player->getName());
$scoreboard->setLine($player, 5, "§fRank: §a" . $userGroup);
$scoreboard->setLine($player, 7, "§fLevel: §a" . $level);
$scoreboard->setLine($player, 10, "§fIP Address:");
$scoreboard->setLine($player, 11, "§emc.happype.us.to");
$scoreboard->setLine($player, 14, "§fShop:");
$scoreboard->setLine($player, 15, "§ewww.happype.tk");

Also I tried creating scoreboard onEnable and access it on task it remove some line

**Comment by MisteFr** [comment]
By executing this code when a player join, you are creating the same scoreboard each time. The consequence is that it reset the previous scoreboard. What you have to do is create a scoreboard for each players
